# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: leEco mobile API
  description: LeEco mobile API
  version: "1.0.0"
# the domain of the service
host: mobile.lecommons.com

# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /LeMobile
produces:
  - application/json
paths:
  /api/auth/{ticket}:
    post:
      tags:
        - "lecommons-mobile"
      summary: "乐盟移动认证接口"
      parameters:
        - name: "ticket"
          in: "path"
          description: "移动端location中ticket的值"
          required: true
          type: "string"
        - name: "body"
          in: "body"
          description: "App的配置信息"
          required: true
          schema:
            $ref: "#/definitions/AppInfo"
      responses:
        200:
          description: string of userinfo/erro message
          schema:
            type: "string"

  /api/send/text/{tabNo}/{appKey}:
    post:
      tags:
        - "lecommons-mobile"
      summary: "乐盟移动待办通知，文本消息发送接口"
      parameters:
        - name: "tabNo"
          in: "path"
          description: "0：发送到待办通知的待办Tab页，1：发送到待办通知的已办Tab页，2：发送到待办通知的通知Tab页"
          required: true
          type: "string"
        - name: "appKey"
          in: "path"
          description: "每个应用有唯一的appkey"
          required: true
          type: "string"
        - name: "body"
          in: "body"
          description: "文本消息信息"
          required: true
          schema:
            $ref: "#/definitions/TextMessage"
      responses:
        200:
          description: An Object of Status
          schema:
            $ref: '#/definitions/Status'

  /api/send/pubacc/text/{appKey}:
    post:
      tags:
        - "lecommons-mobile"
      summary: "乐盟移动公共号通知，文本消息发送接口"
      parameters:
        - name: "appKey"
          in: "path"
          description: "每个应用有唯一的appkey"
          required: true
          type: "string"
        - name: "body"
          in: "body"
          description: "文本消息信息"
          required: true
          schema:
            $ref: "#/definitions/TextMessage"
      responses:
        200:
          description: An Object of Status
          schema:
            $ref: '#/definitions/Status'
definitions:
  AppInfo:
    type: object
    properties:
      appId:
        type: "string"
        description: ""
        format: "string"
      appSecret:
        type: "string"
        format: "string"
      grantType:
        type: "string"
        format: "string"
        description: "固定值"
        enum:
        - "client_credential"
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      body:
        type: object

  TextMessage:
    type: object
    properties:
      accounts:
        type: "array"
        xml:
          name: "accounts"
          wrapped: true
        items:
          type: "string"
      message:
        type: string

